name: Build and deploy Python app to Azure Web App - airparadis

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        cd api
        pip install -r requirements.txt
        
    # Exécuter les tests mais continuer même en cas d'échec
    - name: Run tests
      continue-on-error: true
      run: |
        cd api
        pip install pytest
        pytest

    - name: Create necessary files for deployment
      run: |
        # Créer startup.sh
        cat > api/startup.sh << 'EOF'
        #!/bin/bash
        cd `dirname $0`

        # Définir la variable PORT pour Azure
        export PORT=8000

        # Activer le mode simulation
        export SIMULATION_MODE=true

        # Installer les dépendances
        pip install -r requirements.txt

        # Démarrer l'application
        gunicorn main:app --bind=0.0.0.0:$PORT --timeout 600 --workers 2 --worker-class uvicorn.workers.UvicornWorker
        EOF
        
        # Rendre le script exécutable
        chmod +x api/startup.sh
        
        # Créer .deployment
        cat > api/.deployment << 'EOF'
        [config]
        command = bash startup.sh
        EOF
        
        # Créer web.config
        cat > api/web.config << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <system.webServer>
            <handlers>
              <add name="PythonHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
            </handlers>
            <httpPlatform processPath="%home%\python\3.9\python.exe" 
                          arguments="-m gunicorn main:app --bind=0.0.0.0:%HTTP_PLATFORM_PORT% --timeout 600" 
                          requestTimeout="00:10:00" 
                          startupTimeLimit="300" 
                          startupRetryCount="5" 
                          stdoutLogEnabled="true">
              <environmentVariables>
                <environmentVariable name="PYTHONPATH" value="%home%\site\wwwroot"/>
                <environmentVariable name="PORT" value="%HTTP_PLATFORM_PORT%"/>
                <environmentVariable name="SIMULATION_MODE" value="true"/>
              </environmentVariables>
            </httpPlatform>
          </system.webServer>
        </configuration>
        EOF

    - name: Zip artifact for deployment
      run: |
        cd api
        zip -r ../release.zip ./*

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: |
          release.zip
          !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: python-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      id: deploy-to-webapp
      with:
        app-name: 'airparadis'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EF1A0A46D7FC4FAA838D49433C06F4BD }}